version: '3'
services:
  postgresdb:
    image: "postgres"
    container_name: hmapps-postgres
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=hmapps
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis-devel:
    image: "redis"
    container_name: hmapps-redis
    ports: ["6379:6379"]
