# Generated by Django 2.1.3 on 2019-02-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stt',
            name='duration',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stt',
            name='size',
            field=models.FloatField(default=0),
        ),
    ]
