# Generated by Django 2.1.3 on 2019-02-10 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stt', '0002_auto_20190210_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stt',
            name='size',
        ),
    ]
