# Generated by Django 2.1.3 on 2019-02-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stt', '0003_remove_stt_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='stt',
            name='audio_channels',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='stt',
            name='lang_code',
            field=models.CharField(default='en', max_length=8),
        ),
    ]
