# Generated by Django 2.1.7 on 2019-03-10 11:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stt', '0005_auto_20190301_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stt',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
