# Generated by Django 2.1.7 on 2019-05-18 08:21

from django.db import migrations, models
import django.utils.timezone
import storages.backends.gcloud
import storages.backends.s3boto3
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stt', '0006_auto_20190310_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', versatileimagefield.fields.VersatileImageField(storage=storages.backends.gcloud.GoogleCloudStorage(bucket='pointer-bucket'), upload_to='remember/', verbose_name='Image')),
                ('image_url', models.URLField()),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='stt',
            name='audio',
            field=models.FileField(storage=storages.backends.s3boto3.S3Boto3Storage(bucket='hmapps-audio'), upload_to='input'),
        ),
    ]
