# Generated by Django 2.1.7 on 2019-11-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stt', '0010_auto_20191117_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
