# Generated by Django 2.1.7 on 2019-11-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stt', '0011_auto_20191117_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='page',
        ),
        migrations.AddField(
            model_name='shelf',
            name='page',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
